FROM ubuntu:jammy

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && apt-get install nano
# RUN apt-get update -y && apt-get install -y build-essential r-base \
#     libcurl4-openssl-dev libssl-dev libxml2-dev libharfbuzz-dev \
#     libfontconfig1-dev libfreetype6-dev libtiff5-dev libfribidi-dev

# RUN apt-get update -y && apt-get install -y build-essential
# COPY r-requirements /r-requirements
# RUN cd /r-requirements && Rscript install.R

# Push 1
