export const ALL_COLORS = enabledFeatures.celligner_app_v3
  ? [
      "#008000",
      "#009acd",
      "#00c5cd",
      // "#104e8b",
      "#20b2aa",
      // "#2F4F4F",
      "#458b74",
      "#4682b4",
      "#556b2f",
      "#5cacee",
      "#66cd00",
      "#6B8E23",
      "#6a5acd",
      "#7ccd7c",
      "#8b7500",
      "#9370db",
      // "#9400D3",
      "#9932CC",
      "#9ACD32",
      "#ADD8E6",
      "#DB7093",
      "#EE6A50",
      "#F93C86",
      "#FF087F",
      "#FF7F50",
      "#a2cd5a",
      "#cd4f39",
      "#cd6090",
      "#cd96cd",
      "#daa520",
      "#ee5c42",
      "#ee7621",
      "#f08080",
      "#ff3e96",
    ]
  : [
      "#8a7e79",
      "#80798a",
      "#ffa8b4",
      "#ffa8f9",
      "#a8ffee",
      "#a8e2ff",
      "#ffd7a8",
      "#cbffa8",
      "#fff9a8",
      "#b4a8ff",
      "#a8cbff",
      "#ffbfa8",
      "#b782c4",
      "#c4b782",
      "#82c49c",
      "#aec482",
      "#8293c4",
      "#82c0c4",
      "#c482a5",
      "#c49c82",
      "#c48a82",
      "#7a5b8a",
      "#5b808a",
      "#5b8a74",
      "#5b6e8a",
      "#8a5b5b",
      "#8a745b",
      "#748a5b",
      "#ff70cf",
      "#f5ff70",
      "#8370ff",
      "#cf70ff",
      "#70ffa9",
      "#ffa970",
      "#70a9ff",
      "#ffbc70",
      "#ff7096",
      "#ff8370",
      "#c45665",
      "#c47456",
      "#c4bd56",
      "#c45691",
      "#8a853d",
      "#478a3d",
      "#8a3d85",
      "#3d478a",
      "#8a3d51",
      "#3d8a85",
      "#5b3d8a",
      "#8a5b3d",
      "#8a473d",
      "#ff3853",
      "#ffd738",
      "#a2ff38",
      "#3888ff",
      "#ff38d7",
      "#ff8838",
      "#2bc440",
      "#2bc4ba",
    ];

export const PRIMARY_SITE_COLORS: Array<Plotly.TransformStyle> = enabledFeatures.celligner_app_v3
  ? [
      {
        target: "central_nervous_system",
        value: { marker: { color: "#f5899e" } },
      },
      {
        target: "engineered_central_nervous_system",
        value: { marker: { color: "#f5899e" } },
      },
      { target: "teratoma", value: { marker: { color: "#f5899e" } } },
      { target: "bone", value: { marker: { color: "#9f55bb" } } },
      { target: "pancreas", value: { marker: { color: "#b644dc" } } },
      { target: "soft_tissue", value: { marker: { color: "#5fdb69" } } },
      { target: "skin", value: { marker: { color: "#6c55e2" } } },
      { target: "liver", value: { marker: { color: "#9c5e2b" } } },
      { target: "blood", value: { marker: { color: "#da45bb" } } },
      { target: "lymphocyte", value: { marker: { color: "#abd23f" } } },
      {
        target: "peripheral_nervous_system",
        value: { marker: { color: "#73e03d" } },
      },
      { target: "ovary", value: { marker: { color: "#56e79d" } } },
      { target: "engineered_ovary", value: { marker: { color: "#56e79d" } } },
      { target: "adrenal", value: { marker: { color: "#e13978" } } },
      { target: "adrenal_cortex", value: { marker: { color: "#e13978" } } },
      {
        target: "upper_aerodigestive",
        value: { marker: { color: "#5da134" } },
      },
      { target: "kidney", value: { marker: { color: "#1f8fff" } } },
      {
        target: "engineered_kidney",
        value: { marker: { color: "#1f8fff" } },
      },
      { target: "gastric", value: { marker: { color: "#dfbc3a" } } },
      { target: "eye", value: { marker: { color: "#349077" } } },
      { target: "nasopharynx", value: { marker: { color: "#a9e082" } } },
      { target: "nerve", value: { marker: { color: "#c44c90" } } },
      { target: "unknown", value: { marker: { color: "#999999" } } },
      { target: "cervix", value: { marker: { color: "#5ab172" } } },
      { target: "thyroid", value: { marker: { color: "#d74829" } } },
      { target: "lung", value: { marker: { color: "#51d5e0" } } },
      { target: "engineered_lung", value: { marker: { color: "#51d5e0" } } },
      { target: "rhabdoid", value: { marker: { color: "#d04850" } } },
      { target: "germ_cell", value: { marker: { color: "#75dfbb" } } },
      { target: "embryo", value: { marker: { color: "#75dfbb" } } },
      { target: "colorectal", value: { marker: { color: "#96568e" } } },
      { target: "endocrine", value: { marker: { color: "#d1d684" } } },
      { target: "bile_duct", value: { marker: { color: "#c091e3" } } },
      { target: "pineal", value: { marker: { color: "#949031" } } },
      { target: "thymus", value: { marker: { color: "#659fd9" } } },
      { target: "mesothelioma", value: { marker: { color: "#dc882d" } } },
      { target: "prostate", value: { marker: { color: "#3870c9" } } },
      {
        target: "engineered_prostate",
        value: { marker: { color: "#3870c9" } },
      },
      { target: "uterus", value: { marker: { color: "#e491c1" } } },
      { target: "breast", value: { marker: { color: "#45a132" } } },
      {
        target: "engineered_breast",
        value: { marker: { color: "#45a132" } },
      },
      { target: "urinary_tract", value: { marker: { color: "#e08571" } } },
      { target: "esophagus", value: { marker: { color: "#6a6c2c" } } },
      { target: "fibroblast", value: { marker: { color: "#d8ab6a" } } },
      { target: "plasma_cell", value: { marker: { color: "#e6c241" } } },
    ]
  : [
      {
        target: "central_nervous_system",
        value: { marker: { color: "#8a7e79" } },
      },
      { target: "bone", value: { marker: { color: "#80798a" } } },
      { target: "skin", value: { marker: { color: "#ffa8b4" } } },
      { target: "blood", value: { marker: { color: "#ffa8f9" } } },
      { target: "soft_tissue", value: { marker: { color: "#a8ffee" } } },
      { target: "lymphocyte", value: { marker: { color: "#a8e2ff" } } },
      { target: "pancreas", value: { marker: { color: "#ffd7a8" } } },
      {
        target: "peripheral_nervous_system",
        value: { marker: { color: "#cbffa8" } },
      },
      { target: "ovary", value: { marker: { color: "#fff9a8" } } },
      { target: "liver", value: { marker: { color: "#b4a8ff" } } },
      { target: "adrenal", value: { marker: { color: "#a8cbff" } } },
      {
        target: "upper_aerodigestive",
        value: { marker: { color: "#ffbfa8" } },
      },
      { target: "kidney", value: { marker: { color: "#b782c4" } } },
      { target: "gastric", value: { marker: { color: "#c4b782" } } },
      { target: "eye", value: { marker: { color: "#82c49c" } } },
      { target: "nasopharynx", value: { marker: { color: "#aec482" } } },
      { target: "nerve", value: { marker: { color: "#8293c4" } } },
      { target: "unknown", value: { marker: { color: "#82c0c4" } } },
      { target: "cervix", value: { marker: { color: "#c482a5" } } },
      { target: "thyroid", value: { marker: { color: "#c49c82" } } },
      { target: "lung", value: { marker: { color: "#c48a82" } } },
      { target: "teratoma", value: { marker: { color: "#7a5b8a" } } },
      { target: "germ_cell", value: { marker: { color: "#5b808a" } } },
      { target: "colorectal", value: { marker: { color: "#5b8a74" } } },
      { target: "endocrine", value: { marker: { color: "#5b6e8a" } } },
      { target: "bile_duct", value: { marker: { color: "#8a5b5b" } } },
      { target: "pineal", value: { marker: { color: "#8a745b" } } },
      { target: "thymus", value: { marker: { color: "#748a5b" } } },
      { target: "prostate", value: { marker: { color: "#ff70cf" } } },
      { target: "uterus", value: { marker: { color: "#f5ff70" } } },
      { target: "breast", value: { marker: { color: "#8370ff" } } },
      { target: "urinary_tract", value: { marker: { color: "#cf70ff" } } },
      { target: "esophagus", value: { marker: { color: "#70ffa9" } } },
      { target: "plasma_cell", value: { marker: { color: "#ffa970" } } },
      { target: "fibroblast", value: { marker: { color: "#70a9ff" } } },
      {
        target: "engineered_central_nervous_system",
        value: { marker: { color: "#ffbc70" } },
      },
      {
        target: "engineered_bile_duct",
        value: { marker: { color: "#ff7096" } },
      },
      { target: "embryo", value: { marker: { color: "#ff8370" } } },
      {
        target: "engineered_kidney",
        value: { marker: { color: "#c45665" } },
      },
      { target: "engineered_ovary", value: { marker: { color: "#c47456" } } },
      { target: "engineered", value: { marker: { color: "#c4bd56" } } },
      {
        target: "engineered_prostate",
        value: { marker: { color: "#c45691" } },
      },
      { target: "engineered_lung", value: { marker: { color: "#8a853d" } } },
      { target: "adrenal_cortex", value: { marker: { color: "#478a3d" } } },
      { target: "engineered_blood", value: { marker: { color: "#8a3d85" } } },
      {
        target: "engineered_breast",
        value: { marker: { color: "#3d478a" } },
      },
      {
        target: "epidermoid_carcinoma",
        value: { marker: { color: "#8a3d51" } },
      },
      { target: "other", value: { marker: { color: "#3d8a85" } } },
      { target: "sarcomatoid", value: { marker: { color: "#5b3d8a" } } },
      { target: "gall_bladder", value: { marker: { color: "#8a5b3d" } } },
      { target: "bladder", value: { marker: { color: "#8a473d" } } },
      { target: "parotid", value: { marker: { color: "#ff3853" } } },
      { target: "oral", value: { marker: { color: "#ffd738" } } },
      { target: "None", value: { marker: { color: "#a2ff38" } } },
      { target: "testis", value: { marker: { color: "#3888ff" } } },
      { target: "small_intestine", value: { marker: { color: "#ff38d7" } } },
      {
        target: "autonomic_ganglia",
        value: { marker: { color: "#ff8838" } },
      },
      { target: "meninges", value: { marker: { color: "#2bc440" } } },
      { target: "NS", value: { marker: { color: "#2bc4ba" } } },
    ];
export const PRIMARY_MET_COLORS = enabledFeatures.celligner_app_v3
  ? [
      { target: "N/A", value: { marker: { color: "#20b2aa" } } },
      { target: "Primary Tumor", value: { marker: { color: "#9370db" } } },
      {
        target: "Additional - New Primary",
        value: { marker: { color: "#f08080" } },
      },
      { target: "Metastatic", value: { marker: { color: "#66cd00" } } },
      { target: "Primary", value: { marker: { color: "#009acd" } } },
      { target: "Metastasis", value: { marker: { color: "#f08080" } } },
      { target: "Recurrent Tumor", value: { marker: { color: "#009acd" } } },
      {
        target: "Primary Blood Derived Cancer - Peripheral Blood",
        value: { marker: { color: "#4682b4" } },
      },
      {
        target: "Additional Metastatic",
        value: { marker: { color: "#9370db" } },
      },
      { target: "PRIMARY", value: { marker: { color: "#9400D3" } } },
    ]
  : [
      { target: "N/A", value: { marker: { color: "#b6babf" } } },
      { target: "Primary", value: { marker: { color: "#009acd" } } },
      { target: "Metastasis", value: { marker: { color: "#f08080" } } },
      { target: "Recurrent Tumor", value: { marker: { color: "#66cd00" } } },
    ];
