name: Build app 1

on:
  push:
    paths:
      - 'app1/**'
      - 'app2/**'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build depmap-base docker image
        # run: cd app1 && docker build -t depmap-base .
        run: |
          if [[ -n $(git diff --name-only HEAD^..HEAD app1/) ]]; then
            cd app1 && docker build -t depmap-base .
          fi
        # elif [[ -n $(git diff --name-only HEAD^..HEAD app2/) ]]; then
          #   cd app2 && docker build -t depmap-base .
          # fi


        #   - name: Build and push depmap base docker image
        #   if: ${{ startsWith(github.event.head_commit.modified, 'path1/') }}
        #   run: cd path1 && bash build.sh us.gcr.io/broad-achilles/image1 ga-build-${{ github.run_number }}
        # - name: Build and push depmap base docker image
        #   if: ${{ startsWith(github.event.head_commit.modified, 'path2/') }}
        #   run: cd path2 && bash build.sh us.gcr.io/broad-achilles/image2 ga-build-${{ github.run_number }}


        # if [[ -n $(git diff --name-only HEAD^..HEAD path1/) ]]; then
        #     cd path1 && bash build.sh us.gcr.io/broad-achilles/image1 ga-build-${{ github.run_number }}
        #   elif [[ -n $(git diff --name-only HEAD^..HEAD path2/) ]]; then
        #     cd path2 && bash build.sh us.gcr.io/broad-achilles/image2 ga-build-${{ github.run_number }}
        #   else
        #     echo "No changes detected in monitored paths. Exiting without building."
        #   fi
          # if [[ ${{ github.event.head_commit.modified | join(' ') }} == *"app1/"* ]]; then
          #   cd app1 && docker build -t depmap-base .
          # elif [[ ${{ github.event.head_commit.modified | join(' ') }} == *"app2/"* ]]; then
          #   cd app2 && docker build -t depmap-base .
          # fi
