name: Build app

on: push

env:
  DOCKER_REPO: us.gcr.io/broad-achilles/depmap
  DOCKER_TAG: ga-build-${{ github.run_number }}

jobs:
  run-frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install yarn dependencies
        run: "NODE_OPTIONS='--openssl-legacy-provider' yarn --cwd react_frontend install"
      - name: Build webpack
        run: "NODE_OPTIONS='--openssl-legacy-provider' yarn --cwd react_frontend webpack --config=webpack.prod.js --progress"
      - name: Run tests
        run: yarn --cwd react_frontend jest
        